### ISSUE TITLE
Add new dictionary (download) does not work

### ISSUE THREAD

**Issue by dsalunga** [MCGI/mcgi-bible-ios#5]
The + button does nothing when tapped.

**Comment by dsalunga** [comment]
Same issue for Bible texts

**Comment by 032699** [comment]
San to bro? Nakaka pag install na ko ng Dictionary and bible text. I am
using the installed IPA I generated last night.

**Comment by 032699** [comment]
Do you mean ba sa ADD button sa Bible Page and Dictionary page pag click ng
(+) Add? Dapat nag pupunta to sa downloads? Check ko yung old kung ano
behaviour nya.

**Comment by dsalunga** [comment]
Opo ganun nga. Dapat punta sya sa Downloads pagclick sa Add (+)

**Comment by dsalunga** [comment]
Fixed.
